export const products = [
    {
      id: 1,
      title: "Black cake",
      description: "black in color",
      price: "250",
      img:"https://i.pinimg.com/736x/48/65/f6/4865f65dc9662f05641654500a186eb8.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Kaju Katli",
      description: "white in color",
      price: "550",
      img: "https://www.generalmillsindiabfs.in/wp-content/uploads/2020/11/Pillsbury-India-KajuKatliCake-770x513-1.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Love bite",
      description: "Strawberry",
      price: "350",
      img: "https://justbakedcake.com/wp-content/uploads/2020/09/strawberry-gateaux-1.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Dark jo",
      description: "dark kasatanuts",
      price: "690",
      img: "https://media.bakingo.com/sq-dark-chocolate-cake-cake2070choc-A_0.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "wedding cake",
      description: "black in color",
      price: "250",
      img:"https://i.pinimg.com/736x/48/65/f6/4865f65dc9662f05641654500a186eb8.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Kaju Katli",
      description: "white in color",
      price: "550",
      img: "https://www.generalmillsindiabfs.in/wp-content/uploads/2020/11/Pillsbury-India-KajuKatliCake-770x513-1.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "Love bite",
      description: "Strawberry",
      price: "350",
      img: "https://justbakedcake.com/wp-content/uploads/2020/09/strawberry-gateaux-1.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Dark jo",
      description: "kasatanuts",
      price: "690",
      img: "https://media.bakingo.com/sq-dark-chocolate-cake-cake2070choc-A_0.jpg",
      quantity: 1,
    },
]